### ISSUE TITLE
--verbosity expects a number but was given 'file:<template_dir>/0'

### ISSUE THREAD

**Issue by tomron** [pferrel/template-scala-parallel-universal-recommendation#10]
I run UR version 0.23 with scala 2.10 and pio 0.9.5 and when I run `pio train` I get this error. When I run `pio train --verbosity <number>` it works fine.

In the engine.json file I changed the eventNames and the appName but nothing beside.
I wonder where this parameter comes from.

Also additional question - is `pio deploy` necessary or is it already available after training anyhow?

When I run `pio deploy`, process does not end, it prints `Engine is deployed and running. Engine API is live at http://0.0.0.0:8000` but does not exit the process.
(backend is elasticsearch + hbase + localfs)

**Comment by pferrel** [comment]
you have to give the command line for me to answer you first question.

pio deploy launches a server process, which will stay running until killed. Use `jps -lm | grep onsole` to see which java process is "deploy" and kill it. `pio deploy` creates a PredictionServer for the Universal Recommender so you can send it queries.

BTW you will get quicker responses if you post to the Google Group for PredictionIO
