### ISSUE TITLE
master and v0.3.0* branches to not compile with current PredictionIO release

### ISSUE THREAD

**Issue by jurgispods** [pferrel/template-scala-parallel-universal-recommendation#13]
I can build the v.0.2.3 branch fine with the latest PredictionIO release (0.9.5, installed via the Quick Install script), but the newer branches v0.3.0 and master throw an error when calling 'pio build': The classes io.prediction.core.{EventWindow, SelfCleaningDataSource} are not found - and I can't find them either in the current release or in the Github develop branch.

Which version of PredictionIO is needed to build the master branch of this template and where can I find it?

**Comment by pferrel** [comment]
The release notes point to a new version of PredictionIO from the ActionML fork. See: https://github.com/actionml/template-scala-parallel-universal-recommendation#v030 https://github.com/actionml/template-scala-parallel-universal-recommendation#v030

The repo for PIO is here: https://github.com/actionml/PredictionIO/tree/v0.9.6 https://github.com/actionml/PredictionIO/tree/v0.9.6

On Apr 1, 2016, at 1:36 AM, Jurgis Pods notifications@github.com wrote:

I can build the v.0.2.3 branch fine with the latest PredictionIO release (0.9.5, installed via the Quick Install script), but the newer branches v0.3.0 and master throw an error when calling 'pio build': The classes io.prediction.core.{EventWindow, SelfCleaningDataSource} are not found - and I can't find them either in the current release or in the Github develop branch.

Which version of PredictionIO is needed to build the master branch of this template and where can I find it?

**Comment by jurgispods** [comment]
Ok, thanks. Should have read the release notes more carefully.
